# Site settings
title: Taehoon Park
email: gksdidg@hanyang.ac.kr
url: niai-lab.github.io
description: "NIAI Lab Machine Learning Journal Club"
github_username: niai-lab
meta_author:

# Google webmaster tools
google_verify:

# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Contact form:
# - static : pass through formspree.io to validate email sending
# - disqus : replace contact form by disqus thread
# - comment the line below if you want to stick with the default PHP contact form
contact: static

# If you use disqus you need disqus shortname
# https://help.disqus.com/customer/portal/articles/466208
disqus_shortname:

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: fff #80B3FF
  primary-rgb: "238,238,238" #"128,179,255"
  secondary: 2c3e50 #FD6E8A
  secondary-dark: 233140 #A2122F

# Footer settings
footer:
  copyright: Dr. Henry Jekyll
  location: Location
  social: Around the Web
  credits: Credits

# Build settings
markdown: kramdown
# permalink: pretty

# Plugins
plugins:
  - jekyll-seo-tag

# Other variables
roomH: R&D Building(산학기술관), 702-1
roomHurl: https://www.google.com/maps/place/한양대학교+산학기술관/@37.5554541,127.0492129,17z/data=!4m5!3m4!1s0x357ca5cdf1113cd3:0xd1eef0cf0fed51cd!8m2!3d37.5554541!4d127.0492129

